
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/okumnas/Programs/cmake-3.31.9-linux-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.19.10-arch1-1 - x86_64
...
